name: MegaLinter

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main

jobs:
  build:
    name: MegaLinter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Extract commands from markdown files
        run: |
          set -euxo pipefail
          echo '#!/usr/bin/env bash' > README.sh
          find . -name '*.md' -print0 | while IFS= read -r -d '' FILE ; do
            sed -n "/^\`\`\`\(bash\|shell\).*/,/^\`\`\`$/p" "${FILE}" \
            | \
            sed \
              -e 's/^```\(bash\|shell\).*//' \
              -e '/^```$/d' \
            >> README.sh
          done
          chmod a+x README.sh

      - name: MegaLinter
        uses: megalinter/megalinter@v6.19.0
        env:
          BASH_SHFMT_ARGUMENTS: --indent 2 --space-redirects
          DISABLE_LINTERS: SPELL_CSPELL
          FORMATTERS_DISABLE_ERRORS: false
          GITHUB_COMMENT_REPORTER: false
          GITHUB_STATUS_REPORTER: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_MARKDOWN_LINK_CHECK_FILTER_REGEX_EXCLUDE: tests
          PRINT_ALPACA: false
          SARIF_REPORTER: true
          VALIDATE_ALL_CODEBASE: true
